# Generated by Django 5.2.9 on 2026-03-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
