# Generated by Django 5.2.9 on 2026-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="slot",
            name="end_time",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
    ]
