# Generated by Django 5.0.6 on 2026-04-07 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slot_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={},
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(default=django.utils.timezone.localdate)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('symptoms_text', models.TextField(blank=True, null=True)),
                ('food_type', models.CharField(choices=[('home', 'Normal home food'), ('outside', 'Outside food'), ('junk', 'Junk / oily')], default='home', max_length=20)),
                ('water_intake_glasses', models.PositiveIntegerField(default=0)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sleep_quality', models.CharField(choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good')], default='average', max_length=20)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=100)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('timings', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('prescription_upload', 'Prescription upload')], default='manual', max_length=30)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_date', models.DateField()),
                ('timing', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='api.medicationschedule')),
            ],
            options={
                'ordering': ['-dose_date', 'timing'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyhealthlog',
            constraint=models.UniqueConstraint(fields=('user', 'log_date'), name='unique_daily_health_log_per_user'),
        ),
        migrations.AddConstraint(
            model_name='medicationdoselog',
            constraint=models.UniqueConstraint(fields=('medication', 'dose_date', 'timing'), name='unique_medication_dose_log'),
        ),
    ]
