# Generated by Django 5.0.6 on 2026-04-07 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_passwordresetotp_options_alter_message_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(blank=True, default=django.utils.timezone.localdate, null=True)),
                ('input_message', models.TextField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('symptoms_text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('food_type', models.CharField(blank=True, choices=[('home', 'Normal home food'), ('outside', 'Outside food'), ('junk', 'Junk / oily')], max_length=20)),
                ('water_intake_glasses', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good')], max_length=20)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('energy_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('matched_symptoms', models.JSONField(blank=True, default=list)),
                ('detected_problem', models.CharField(max_length=200)),
                ('risk_probability', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('model_name', models.CharField(default='LogisticRegression', max_length=100)),
                ('top_predictions', models.JSONField(blank=True, default=list)),
                ('reference_symptoms', models.JSONField(blank=True, default=list)),
                ('care_guidance', models.JSONField(blank=True, default=list)),
                ('medicine_guidance', models.JSONField(blank=True, default=list)),
                ('warning_signs', models.JSONField(blank=True, default=list)),
                ('submitted_context', models.JSONField(blank=True, default=list)),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('assistant_response', models.TextField()),
                ('response_language', models.CharField(choices=[('english', 'English'), ('hinglish', 'Hinglish')], default='english', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_analysis_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
